"use client";

import { Camera, CameraOff, LoaderCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { ProtectedFeaturePage } from "@/components/layout/ProtectedFeaturePage";
import { Button } from "@/components/ui/Button";
import { analyzePose } from "@/services/aiService";

const index={shoulder:11,elbow:13,wrist:15,hip:23,knee:25,ankle:27};
export default function FormCheckPage(){
 const video=useRef(null),canvas=useRef(null),stream=useRef(null),landmarker=useRef(null),frame=useRef(null),lastSent=useRef(0);
 const [exercise,setExercise]=useState("squat"),[running,setRunning]=useState(false),[loading,setLoading]=useState(false),[result,setResult]=useState(null),[error,setError]=useState("");
 useEffect(()=>()=>stop(),[]);
 async function start(){setLoading(true);setError("");try{const {FilesetResolver,PoseLandmarker}=await import("@mediapipe/tasks-vision");const vision=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm");landmarker.current=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task",delegate:"CPU"},runningMode:"VIDEO",numPoses:1});stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});video.current.srcObject=stream.current;await video.current.play();setRunning(true);loop();}catch(e){setError("Camera-based form checking could not start. Check camera permission and network access for the local pose model runtime.");}finally{setLoading(false);}}
 function stop(){if(frame.current)cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());landmarker.current?.close?.();stream.current=null;landmarker.current=null;setRunning(false);}
 async function loop(){if(!video.current||!landmarker.current)return;const now=performance.now(),pose=landmarker.current.detectForVideo(video.current,now).landmarks?.[0];draw(pose);if(pose&&now-lastSent.current>500){lastSent.current=now;const landmarks=Object.entries(index).map(([name,i])=>({name,x:pose[i].x,y:pose[i].y,visibility:pose[i].visibility||0}));try{setResult(await analyzePose({exercise,landmarks,timestamp:Date.now()/1000}));}catch{setError("Form feedback is temporarily unavailable; camera processing remains on this device.");}}frame.current=requestAnimationFrame(loop);}
 function draw(points){const ctx=canvas.current?.getContext("2d");if(!ctx)return;canvas.current.width=video.current.videoWidth;canvas.current.height=video.current.videoHeight;ctx.clearRect(0,0,canvas.current.width,canvas.current.height);if(!points)return;ctx.fillStyle="#b8d8b2";for(const p of points){ctx.beginPath();ctx.arc(p.x*canvas.current.width,p.y*canvas.current.height,3,0,Math.PI*2);ctx.fill();}}
 return <ProtectedFeaturePage title="Form checker" description="Camera frames stay on your device. ZenFit sends sampled pose landmarks—not video—for basic, non-medical exercise feedback."><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="panel rounded-2xl p-4"><select className="mb-4 rounded-xl bg-black/30 px-3 py-2" value={exercise} onChange={e=>setExercise(e.target.value)}>{[["squat","Squat"],["pushup","Push-up"],["lunge","Lunge"],["shoulder_press","Shoulder Press"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><video ref={video} muted playsInline className="h-full w-full -scale-x-100 object-cover"/><canvas ref={canvas} className="pointer-events-none absolute inset-0 h-full w-full -scale-x-100"/></div><Button className="mt-4" onClick={running?stop:start}>{loading?<LoaderCircle className="animate-spin"/>:running?<CameraOff/>:<Camera/>}{running?"Stop camera":"Start camera"}</Button>{error?<p className="mt-3 text-sm text-coralGlow">{error}</p>:null}</section><section className="panel rounded-2xl p-5"><p className="text-sm text-muted">Reps</p><p className="mt-1 text-5xl font-semibold">{result?.reps||0}</p><p className="mt-5 text-sm text-muted">Range of motion</p><p className="mt-1 text-xl">{result?.joint_angle?`${result.joint_angle}°`:"Waiting for movement"}</p><div className="mt-5 space-y-2">{(result?.observations||[]).map(item=><p key={item} className="rounded-xl bg-white/5 p-3 text-sm">{item==="limited_range_of_motion"?"Try moving through a comfortable, slightly fuller range.":item}</p>)}</div><p className="mt-6 text-xs text-muted">This is basic movement feedback, not diagnosis or medical assessment.</p></section></div></ProtectedFeaturePage>;
}
